"""Migrations must import, apply, and match the models.

Autogenerated revisions have been known to reference names they never import
(`Text()` without `sa.`), which only fails at deploy time. This runs them.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory

from app.models import Base

BACKEND = Path(__file__).resolve().parents[1]


def _config(db_path: Path) -> Config:
    cfg = Config(str(BACKEND / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND / "alembic"))
    # Alembic's env.py reads the URL from settings, so override it there too.
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    return cfg


def test_every_revision_imports() -> None:
    """Catches NameError and bad imports inside a revision module."""
    script = ScriptDirectory(str(BACKEND / "alembic"))
    revisions = list(script.walk_revisions())

    assert revisions, "no migrations found"
    for rev in revisions:
        assert rev.module is not None
        assert hasattr(rev.module, "upgrade")
        assert hasattr(rev.module, "downgrade")


def test_upgrade_head_creates_every_model_table(tmp_path: Path, monkeypatch) -> None:
    db = tmp_path / "migrate.db"
    monkeypatch.setenv("SDWAN_DATABASE_URL", f"sqlite+aiosqlite:///{db}")

    # Settings are cached; drop the cache so env.py picks up the test URL.
    from app.config import get_settings

    get_settings.cache_clear()
    try:
        command.upgrade(_config(db), "head")
    finally:
        get_settings.cache_clear()

    con = sqlite3.connect(db)
    try:
        created = {
            row[0]
            for row in con.execute("select name from sqlite_master where type='table'")
        }
    finally:
        con.close()

    expected = set(Base.metadata.tables)
    missing = expected - created
    assert not missing, f"migration does not create: {sorted(missing)}"
