"""Migrations must import, apply, and match the models.

Autogenerated revisions have been known to reference names they never import
(`Text()` without `sa.`), which only fails at deploy time. This runs them.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory

from app.models import Base

BACKEND = Path(__file__).resolve().parents[1]


def _config(db_path: Path) -> Config:
    cfg = Config(str(BACKEND / "alembic.ini"))
    cfg.set_main_option("script_location", str(BACKEND / "alembic"))
    # Alembic's env.py reads the URL from settings, so override it there too.
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    return cfg


def test_every_revision_imports() -> None:
    """Catches NameError and bad imports inside a revision module."""
    script = ScriptDirectory(str(BACKEND / "alembic"))
    revisions = list(script.walk_revisions())

    assert revisions, "no migrations found"
    for rev in revisions:
        assert rev.module is not None
        assert hasattr(rev.module, "upgrade")
        assert hasattr(rev.module, "downgrade")


def test_upgrade_head_creates_every_model_table(tmp_path: Path, monkeypatch) -> None:
    db = tmp_path / "migrate.db"
    monkeypatch.setenv("SDWAN_DATABASE_URL", f"sqlite+aiosqlite:///{db}")

    # Settings are cached; drop the cache so env.py picks up the test URL.
    from app.config import get_settings

    get_settings.cache_clear()
    try:
        command.upgrade(_config(db), "head")
    finally:
        get_settings.cache_clear()

    con = sqlite3.connect(db)
    try:
        created = {
            row[0]
            for row in con.execute("select name from sqlite_master where type='table'")
        }
    finally:
        con.close()

    expected = set(Base.metadata.tables)
    missing = expected - created
    assert not missing, f"migration does not create: {sorted(missing)}"


def _upgrade_to(db: Path, revision: str, monkeypatch) -> None:
    monkeypatch.setenv("SDWAN_DATABASE_URL", f"sqlite+aiosqlite:///{db}")
    from app.config import get_settings

    get_settings.cache_clear()
    try:
        command.upgrade(_config(db), revision)
    finally:
        get_settings.cache_clear()


def test_existing_rules_are_moved_onto_groups(tmp_path: Path, monkeypatch) -> None:
    """The SD-WAN group migration carries data, not just schema.

    A rule whose uplink order and SLA were retyped into it must come out the
    other side pointing at a group that means the same thing -- otherwise the
    upgrade silently un-steers every policy on the box.
    """
    db = tmp_path / "groups.db"
    _upgrade_to(db, "b41c7ea9d5c2", monkeypatch)

    con = sqlite3.connect(db)
    try:
        con.execute(
            "INSERT INTO sla_profiles (id, tenant_id, name, loss_percent, latency_ms,"
            " probe_interval_seconds, probe_count, recovery_seconds,"
            " created_at, updated_at)"
            " VALUES ('sla-1', 'default', 'voice', 1, 150, 5, 10, 60,"
            " CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
        )
        for pid, name, tags in (
            ("p1", "teams", '["fibre", "lte"]'),
            # Same uplinks and same SLA: must share one group, not get a
            # near-duplicate each.
            ("p2", "sip", '["fibre", "lte"]'),
            ("p3", "backup", '["lte"]'),
            # No uplinks at all: already inert, and must not invent a group.
            ("p4", "empty", "[]"),
        ):
            con.execute(
                "INSERT INTO policies (id, tenant_id, name, priority, enabled,"
                " prefer_tags, sla_profile_id, fallback, created_at, updated_at)"
                " VALUES (?, 'default', ?, 100, 1, ?, 'sla-1', 'any',"
                " CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                (pid, name, tags),
            )
        con.commit()
    finally:
        con.close()

    _upgrade_to(db, "head", monkeypatch)

    con = sqlite3.connect(db)
    try:
        groups = {
            row[0]: row for row in con.execute("SELECT id, name, members, strategy,"
                                               " sla_profile_id FROM sdwan_groups")
        }
        linked = dict(con.execute("SELECT name, sdwan_group_id FROM policies"))
    finally:
        con.close()

    assert len(groups) == 2, f"expected one group per distinct path, got {groups}"
    assert linked["teams"] == linked["sip"], "identical paths must share a group"
    assert linked["backup"] not in (None, linked["teams"])
    assert linked["empty"] is None, "a rule with no uplinks gets no group"

    shared = groups[linked["teams"]]
    assert json.loads(shared[2]) == [
        {"uplink": "fibre", "weight": 1},
        {"uplink": "lte", "weight": 1},
    ], "order is the preference and must survive"
    assert shared[3] == "failover"
    assert shared[4] == "sla-1", "the SLA moves with the path"
