"""policies, sla profiles, app groups

Revision ID: 00c9a63a7c88
Revises: a7d7dbefeae0
Create Date: 2026-09-05 11:10:00.691774
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '00c9a63a7c88'
down_revision: str | None = 'a7d7dbefeae0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_groups',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prefixes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ports', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('dscp', sa.Integer(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_appgroup_tenant_name')
    )
    op.create_index(op.f('ix_app_groups_name'), 'app_groups', ['name'], unique=False)
    op.create_index(op.f('ix_app_groups_tenant_id'), 'app_groups', ['tenant_id'], unique=False)
    op.create_table('sla_profiles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('loss_percent', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('jitter_ms', sa.Integer(), nullable=True),
    sa.Column('probe_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('probe_count', sa.Integer(), nullable=False),
    sa.Column('recovery_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_sla_tenant_name')
    )
    op.create_index(op.f('ix_sla_profiles_name'), 'sla_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_sla_profiles_tenant_id'), 'sla_profiles', ['tenant_id'], unique=False)
    op.create_table('policies',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('fabric_id', sa.String(length=36), nullable=True),
    sa.Column('site_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('src_prefixes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('dst_prefixes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('app_group_id', sa.String(length=36), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('dst_ports', sa.String(length=128), nullable=True),
    sa.Column('dscp', sa.Integer(), nullable=True),
    sa.Column('prefer_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sla_profile_id', sa.String(length=36), nullable=True),
    sa.Column('fallback', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['app_group_id'], ['app_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sla_profile_id'], ['sla_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_policy_tenant_name')
    )
    op.create_index(op.f('ix_policies_fabric_id'), 'policies', ['fabric_id'], unique=False)
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=False)
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_index(op.f('ix_policies_fabric_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_sla_profiles_tenant_id'), table_name='sla_profiles')
    op.drop_index(op.f('ix_sla_profiles_name'), table_name='sla_profiles')
    op.drop_table('sla_profiles')
    op.drop_index(op.f('ix_app_groups_tenant_id'), table_name='app_groups')
    op.drop_index(op.f('ix_app_groups_name'), table_name='app_groups')
    op.drop_table('app_groups')
    # ### end Alembic commands ###
