"""pin device identity

Revision ID: a63884a33993
Revises: 00c9a63a7c88
Create Date: 2026-09-05 16:33:50.358606
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a63884a33993'
down_revision: str | None = '00c9a63a7c88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('tls_fingerprint', sa.String(length=95), nullable=True))
    op.add_column('sites', sa.Column('ssh_host_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'ssh_host_key')
    op.drop_column('sites', 'tls_fingerprint')
    # ### end Alembic commands ###
