"""initial schema

Revision ID: a7d7dbefeae0
Revises: 
Create Date: 2026-09-04 16:50:21.833622
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a7d7dbefeae0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_object_id'), 'audit_events', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_events_object_type'), 'audit_events', ['object_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('fabrics',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=24), nullable=False),
    sa.Column('transport_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('topology', sa.String(length=24), nullable=False),
    sa.Column('ip_pool', sa.String(length=64), nullable=False),
    sa.Column('loopback_pool', sa.String(length=64), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('mtu', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_fabric_tenant_name')
    )
    op.create_index(op.f('ix_fabrics_name'), 'fabrics', ['name'], unique=False)
    op.create_index(op.f('ix_fabrics_tenant_id'), 'fabrics', ['tenant_id'], unique=False)
    op.create_table('sites',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('mgmt_host', sa.String(length=255), nullable=False),
    sa.Column('mgmt_port', sa.Integer(), nullable=True),
    sa.Column('device_kind', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.Column('ssh_key_enc', sa.Text(), nullable=True),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('ros_version', sa.String(length=32), nullable=True),
    sa.Column('board_name', sa.String(length=128), nullable=True),
    sa.Column('architecture', sa.String(length=32), nullable=True),
    sa.Column('identity', sa.String(length=128), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_seen_at', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('loopback_ip', sa.String(length=64), nullable=True),
    sa.Column('local_prefixes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rollback_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('drift_action', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_site_tenant_name')
    )
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_index(op.f('ix_sites_region'), 'sites', ['region'], unique=False)
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('fabric_members',
    sa.Column('fabric_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('role_override', sa.String(length=16), nullable=True),
    sa.Column('loopback_ip', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fabric_id', 'site_id', name='uq_member_fabric_site')
    )
    op.create_index(op.f('ix_fabric_members_fabric_id'), 'fabric_members', ['fabric_id'], unique=False)
    op.create_index(op.f('ix_fabric_members_site_id'), 'fabric_members', ['site_id'], unique=False)
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('fabric_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rollback_token', sa.String(length=64), nullable=True),
    sa.Column('backup_name', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_fabric_id'), 'jobs', ['fabric_id'], unique=False)
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_site_id'), 'jobs', ['site_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('wans',
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('interface', sa.String(length=64), nullable=False),
    sa.Column('public_ip', sa.String(length=64), nullable=True),
    sa.Column('dynamic', sa.Boolean(), nullable=False),
    sa.Column('nat_behind', sa.Boolean(), nullable=False),
    sa.Column('gateway', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('bandwidth_mbps', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_wan_site_name')
    )
    op.create_index(op.f('ix_wans_site_id'), 'wans', ['site_id'], unique=False)
    op.create_table('links',
    sa.Column('fabric_id', sa.String(length=36), nullable=False),
    sa.Column('a_wan_id', sa.String(length=36), nullable=False),
    sa.Column('b_wan_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('a_tunnel_ip', sa.String(length=64), nullable=False),
    sa.Column('b_tunnel_ip', sa.String(length=64), nullable=False),
    sa.Column('subnet', sa.String(length=64), nullable=False),
    sa.Column('initiator', sa.String(length=1), nullable=False),
    sa.Column('dynamic', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('secrets_enc', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['a_wan_id'], ['wans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['b_wan_id'], ['wans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fabric_id', 'a_wan_id', 'b_wan_id', name='uq_link_fabric_pair')
    )
    op.create_index(op.f('ix_links_a_wan_id'), 'links', ['a_wan_id'], unique=False)
    op.create_index(op.f('ix_links_b_wan_id'), 'links', ['b_wan_id'], unique=False)
    op.create_index(op.f('ix_links_fabric_id'), 'links', ['fabric_id'], unique=False)
    op.create_index(op.f('ix_links_slug'), 'links', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_slug'), table_name='links')
    op.drop_index(op.f('ix_links_fabric_id'), table_name='links')
    op.drop_index(op.f('ix_links_b_wan_id'), table_name='links')
    op.drop_index(op.f('ix_links_a_wan_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_wans_site_id'), table_name='wans')
    op.drop_table('wans')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_site_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_fabric_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_fabric_members_site_id'), table_name='fabric_members')
    op.drop_index(op.f('ix_fabric_members_fabric_id'), table_name='fabric_members')
    op.drop_table('fabric_members')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_region'), table_name='sites')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_fabrics_tenant_id'), table_name='fabrics')
    op.drop_index(op.f('ix_fabrics_name'), table_name='fabrics')
    op.drop_table('fabrics')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_object_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_object_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
